### ISSUE TITLE
update deps version? mir-algorithm is v3.9.2  now

### ISSUE THREAD

**Issue by mw66** [tastyminerals/pretty-d-array#6]

**Comment by tastyminerals** [comment]
updated to `3.9.2`

**Comment by mw66** [comment]
you need to make a new release, otherwise dub will not pick it up.

**Comment by mw66** [comment]
hit this version problem again:

```
  mir-stat 0.0.10 depends on mir-algorithm >=3.9.60
  pretty_array 1.0.2 depends on mir-algorithm ~>3.9.2
```

If there is no real hard constraint of pretty_array on a specific mir-algorithm version, can we relax the version specification not depending on a specific version?  Otherwise each time mir-algorithm upgrade version, this pretty_array package also need upgrade purely for the version compatibility.

**Comment by tastyminerals** [comment]
There is no real hard constraint. Just forgot about `~>` dependency syntax. I updated the dub config and _moved_ the git `v1.0.2` tag to the updated version.
